In [2]:
## Lets see more complex data

# make a prediction logistic regression model
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
# define dataset
X, y = make_classification(n_samples=1000, n_features=10, n_informative=5, n_redundant=5, n_classes=2, random_state=1)

In [3]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

## Logisitic Regression Hyperparameter Tuning

## Model Training Hyperparameter Tuning
## GridsearchCV

In [4]:
from sklearn.model_selection import GridSearchCV
import warnings
warnings.filterwarnings('ignore')

In [5]:
parameters={'penalty':('l1', 'l2','elasticnet'),'C':[1,10,20,30]}

In [6]:
classifier=LogisticRegression()

In [7]:
clf=GridSearchCV(classifier,param_grid=parameters,cv=5)

In [8]:
## Splitting of Training data to train and validation
clf.fit(X_train,y_train)

,estimator,LogisticRegression()
,param_grid,"{'C': [1, 10, ...], 'penalty': ('l1', ...)}"
,scoring,None
,n_jobs,None
,refit,True
,cv,5
,verbose,0
,pre_dispatch,'2*n_jobs'
,error_score,nan
,return_train_score,False
,penalty,'l2'


In [9]:
clf.best_params_

{'C': 1, 'penalty': 'l2'}

In [10]:
clf.best_score_

np.float64(0.8087500000000001)

In [11]:
classifier=LogisticRegression(C=1,penalty='l2')

In [12]:
classifier.fit(X_train,y_train)

,penalty,'l2'
,dual,False
,tol,0.0001
,C,1
,fit_intercept,True
,intercept_scaling,1
,class_weight,None
,random_state,None
,solver,'lbfgs'
,max_iter,100
,multi_class,'deprecated'


In [13]:
y_pred=classifier.predict(X_test)

In [14]:
y_pred

array([0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       0, 1])

In [15]:
classifier.predict_proba(X_test)

array([[0.71651923, 0.28348077],
       [0.1950465 , 0.8049535 ],
       [0.12414182, 0.87585818],
       [0.05044049, 0.94955951],
       [0.8877372 , 0.1122628 ],
       [0.75067873, 0.24932127],
       [0.97980988, 0.02019012],
       [0.39209128, 0.60790872],
       [0.59915467, 0.40084533],
       [0.39298278, 0.60701722],
       [0.20417269, 0.79582731],
       [0.80256674, 0.19743326],
       [0.8642444 , 0.1357556 ],
       [0.92666604, 0.07333396],
       [0.00131606, 0.99868394],
       [0.04168894, 0.95831106],
       [0.56294841, 0.43705159],
       [0.89322189, 0.10677811],
       [0.29273031, 0.70726969],
       [0.00870462, 0.99129538],
       [0.71874782, 0.28125218],
       [0.51089475, 0.48910525],
       [0.76228576, 0.23771424],
       [0.73168731, 0.26831269],
       [0.10152661, 0.89847339],
       [0.04045506, 0.95954494],
       [0.57929547, 0.42070453],
       [0.00526033, 0.99473967],
       [0.03099815, 0.96900185],
       [0.96092766, 0.03907234],
       [0.

In [16]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [17]:
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[78 13]
 [29 80]]
0.79
              precision    recall  f1-score   support

           0       0.73      0.86      0.79        91
           1       0.86      0.73      0.79       109

    accuracy                           0.79       200
   macro avg       0.79      0.80      0.79       200
weighted avg       0.80      0.79      0.79       200



## Randomized Search cv

In [18]:
from sklearn.model_selection import RandomizedSearchCV

In [19]:
random_clf=RandomizedSearchCV(LogisticRegression(),param_distributions=parameters,cv=5,n_iter=20)

In [20]:
random_clf

,estimator,LogisticRegression()
,param_distributions,"{'C': [1, 10, ...], 'penalty': ('l1', ...)}"
,n_iter,20
,scoring,None
,n_jobs,None
,refit,True
,cv,5
,verbose,0
,pre_dispatch,'2*n_jobs'
,random_state,None
,error_score,nan


In [21]:
random_clf.fit(X_train,y_train)

,estimator,LogisticRegression()
,param_distributions,"{'C': [1, 10, ...], 'penalty': ('l1', ...)}"
,n_iter,20
,scoring,None
,n_jobs,None
,refit,True
,cv,5
,verbose,0
,pre_dispatch,'2*n_jobs'
,random_state,None
,error_score,nan


In [22]:
random_clf.best_params_

{'penalty': 'l2', 'C': 1}